# Generated by Django 6.0.6 on 2026-09-11 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_appmodule_sdk_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='accent_color',
            field=models.CharField(default='#059669', help_text='Color de acento de marca institucional en formato hexadecimal, ej. #059669.', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser un valor hexadecimal válido, por ejemplo #6B1D2F.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de Acento (HEX)'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='primary_color',
            field=models.CharField(default='#6B1D2F', help_text='Color primario de marca institucional en formato hexadecimal, ej. #6B1D2F.', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser un valor hexadecimal válido, por ejemplo #6B1D2F.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color Primario (HEX)'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='secondary_color',
            field=models.CharField(default='#4A5568', help_text='Color secundario de marca institucional en formato hexadecimal, ej. #4A5568.', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser un valor hexadecimal válido, por ejemplo #6B1D2F.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color Secundario (HEX)'),
        ),
    ]
