# Generated by Django 6.0.6 on 2026-09-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_tenantconfig_branding_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='enable_whatsapp_support',
            field=models.BooleanField(default=True, help_text='Activa el botón flotante de contacto por WhatsApp en la portada pública.', verbose_name='Habilitar Soporte por WhatsApp'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número institucional con código de país, solo dígitos. Ej. 5219211234567.', max_length=20, verbose_name='Número de WhatsApp Institucional'),
        ),
    ]
