# Generated by Django 6.0.6 on 2026-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_tenantconfig_enable_whatsapp_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='show_whatsapp_on_public_landing',
            field=models.BooleanField(default=True, help_text='Controla si el botón flotante de WhatsApp aparece en la portada pública del Core.', verbose_name='Mostrar WhatsApp en Portada Pública'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='whatsapp_default_message',
            field=models.CharField(blank=True, default='Hola, necesito asistencia en el Portal Digital de Axentra OS.', help_text='Mensaje precargado que el ciudadano ve al abrir la conversación de WhatsApp.', max_length=255, verbose_name='Mensaje Inicial de WhatsApp'),
        ),
    ]
